### ISSUE TITLE
InterruptReminder

### ISSUE THREAD

**Issue by Fabricatedhero** [AgentRG/WoW-Addons#29]
Hi, I saw this addon and decided to try it out, but I am getting the below error.

4x InterruptReminder/Libs/LibFramePool-1.0-0/LibFramePool-1.0.lua:1 Error loading InterruptReminder/Libs/LibFramePool-1.0/LibFramePool-1.0.lua

I installed LibFramePool from Curseforge to see if that would fix it but it does not.

**Comment by AgentRG** [comment]
Oh oh! That must've been broken for a while! Two weeks, actually! Thanks for letting me know! The issue was that the compressed add-on on CurseForge was missing that library because I forgot to include it in the archive. I just pushed a fix called [v2.1.5](https://legacy.curseforge.com/wow/addons/interruptreminder/files/5289199). CurseForge is in the process of reviewing it and it should be available in a few minutes/hours.

**Comment by Fabricatedhero** [comment]
awesome on the response time..i shall give a go : )

**Comment by Fabricatedhero** [comment]
its loads and no error and i can get to the settings but anytime I click on a target i get this error...

10x ...rfaceInterruptReminder/InterruptReminder.lua:1086: attempt to call method 'GetPagedID' (a nil value)
[string "@InterruptReminder/InterruptReminder.lua"]:1086: in function `find_button'
[string "@InterruptReminder/InterruptReminder.lua"]:1114: in function `FindSpellLocation'
[string "@InterruptReminder/InterruptReminder.lua"]:1247: in function `Handle_TargetStoppedCasting'
[string "@InterruptReminder/InterruptReminder.lua"]:1331: in function `Handle_PlayerSwitchingTargets'
[string "@InterruptReminder/InterruptReminder.lua"]:1406: in function <...rfaceInterruptReminder/InterruptReminder.lua:1394>

Locals:
actionBars = <table> {
 1 = "ElvUI_Bar1Button"
 2 = "ElvUI_Bar2Button"
 3 = "ElvUI_Bar3Button"
 4 = "ElvUI_Bar4Button"
 5 = "ElvUI_Bar5Button"
 6 = "ElvUI_Bar6Button"
 7 = "ElvUI_Bar7Button"
 8 = "ElvUI_Bar8Button"
 9 = "ElvUI_Bar9Button"
 10 = "ElvUI_Bar10Button"
 11 = "ElvUI_Bar13Button"
 12 = "ElvUI_Bar14Button"
 13 = "ElvUI_Bar15Button"
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "ElvUI_Bar1Button"
 2 = "ElvUI_Bar2Button"
 3 = "ElvUI_Bar3Button"
 4 = "ElvUI_Bar4Button"
 5 = "ElvUI_Bar5Button"
 6 = "ElvUI_Bar6Button"
 7 = "ElvUI_Bar7Button"
 8 = "ElvUI_Bar8Button"
 9 = "ElvUI_Bar9Button"
 10 = "ElvUI_Bar10Button"
 11 = "ElvUI_Bar13Button"
 12 = "ElvUI_Bar14Button"
 13 = "ElvUI_Bar15Button"
}
(for control) = 5
_ = 5
barName = "ElvUI_Bar5Button"
(for index) = 1
(for limit) = 12
(for step) = 1
i = 1
button = ElvUI_Bar5Button1 {
 0 = <userdata>
 FlyoutArrowContainer = Frame {
 }
 NewActionTexture = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 UpdateButtonArt = <function> defined @FrameXML/ActionButton.lua:1514
 TargetReticleAnimFrame = Frame {
 }
 icon = ElvUI_Bar5Button1Icon {
 }
 SlotArt = Texture {
 }
 AutoCastable = Texture {
 }
 keyBoundTarget = "MULTIACTIONBAR2BUTTON1"
 InterruptDisplay = Frame {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 glossTex = true
 HotKey = ElvUI_Bar5Button1HotKey {
 }
 HighlightTexture = Texture {
 }
 PixelSnapDisabled = true
 CooldownFlash = Frame {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 IconMask = MaskTexture {
 }
 db = <table> {
 }
 hover = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 TopEdge = Texture {
 }
 PushedTexture = Texture {
 }
 config = <table> {
 }
 Count = ElvUI_Bar5Button1Count {
 }
 _state_type = "empty"
 state_types = <table> {
 }
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 state_actions = <table> {
 }
 GetShowGrid = <function> defined @FrameXML/ActionButton.lua:1496
 MasqueSkinned = true
 Flash = ElvUI_Bar5Button1Flash {
 }
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 SpellCastAnimFrame = Frame {
 }
 LevelLinkLockIcon = Texture {
 }
 pushed = Texture {
 }
 template = "Default"
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 FlyoutBorderShadow = ElvUI_Bar5Button1FlyoutBorderShadow {
 }
 shadow = Frame {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 FlyoutUpdateFunc = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1515
 AuraCooldown = Cooldown {
 }
 checked = Texture {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 BottomEdge = Texture {
 }
 action = 0
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 CalculateAction = <function> defined @FrameXML/SecureTemplates.lua:609
 parentName = "ElvUI_Bar5"
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 BaseActionButtonMixin_OnLoad = <function> defined @FrameXML/ActionButton.lua:1489
 handleBackdrop = true
 Border = ElvUI_Bar5Button1Border {
 }
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 postKeybind = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1412
 CheckedTexture = Texture {
 }
 id = 1
 SetShowGrid = <function> defined @FrameXML/ActionButton.lua:1501
 SpellH

**Comment by AgentRG** [comment]
Do you have ElvUI enabled by any chance? If so, can you export your UI config and post it here so I can import it and see for myself? I do officially support ElvUI, but it looks like for whatever reason, the button that it found on an actionbar is not actually an actionbar button, so I'm wondering what it is.

**Comment by AgentRG** [comment]
@Fabricatedhero I have not heard from you in two weeks, so I'll assume the issue has been resolved or became a non-issue. I will close this issue now, but feel free to reopen need.
