### ISSUE TITLE
InterruptReminder.lua:963: bad argument #1 to 'concat' (table expected, got nil)

### ISSUE THREAD

**Issue by Tayedaen** [AgentRG/WoW-Addons#68]
Hi,

I've encountered an error with InterruptReminder while loading my hunter character.
Can you please look at this?

The error also occurs if InterruptReminder is the only active addon.

BR

2x ...rfaceInterruptReminder/InterruptReminder.lua:963: bad argument #1 to 'concat' (table expected, got nil)
[string "=[C]"]: in function `concat'
[string "@InterruptReminder/InterruptReminder.lua"]:963: in function `CreateInterface'
[string "@InterruptReminder/InterruptReminder.lua"]:1433: in function <...rfaceInterruptReminder/InterruptReminder.lua:1432>

Locals:
(*temporary) = nil
(*temporary) = ","
(*temporary) = "table expected, got nil"

**Comment by Tayedaen** [comment]
Looking into the code I think the error occurs because the addon is only intended to work with an english client.
Since my client is running in german (deDE) the whole thing is not working due to missing localization.
Perhaps you should add a notice to the CurseForge page to indicate that fact.

Or better : Add localization for the classses and switch from Spell names to Spell IDs ;-)

**Comment by AgentRG** [comment]
That would be correct assumption. I do not have any localization in the code. Now that I know I have non-English audience, I probably need to switch to using spell ids. I'll set it as my big next change.

**Comment by AgentRG** [comment]
@Tayedaen I have resolved this issue in the latest update. I got rid of the smart spell lookup that relied on keywords and migrated to using hard-coded spell IDs. The mod should now work in German clients. Although all the text inside the mod is still English.
